# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
volumes:
  postgres:
services:
  db-test:
    image: postgres:15
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  postgres:
    image: postgres:15
    restart: always
    container_name: dev-db
    environment:
      POSTGRES_USER: prismadev
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: scheduletasks
    ports:
      - '5432:5432'